/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_sed_soda_data_CoverageMatrix */

#ifndef _Included_hu_sed_soda_data_CoverageMatrix
#define _Included_hu_sed_soda_data_CoverageMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_sed_soda_data_CoverageMatrix
 * Method:    addTestcaseName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_CoverageMatrix_addTestcaseName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hu_sed_soda_data_CoverageMatrix
 * Method:    addCodeElementName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_CoverageMatrix_addCodeElementName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hu_sed_soda_data_CoverageMatrix
 * Method:    refitMatrixSize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_CoverageMatrix_refitMatrixSize
  (JNIEnv *, jobject);

/*
 * Class:     hu_sed_soda_data_CoverageMatrix
 * Method:    setRelation
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_CoverageMatrix_setRelation
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     hu_sed_soda_data_CoverageMatrix
 * Method:    save
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_CoverageMatrix_save
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hu_sed_soda_data_CoverageMatrix
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_CoverageMatrix_initialise
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
