/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_sed_soda_data_Changeset */

#ifndef _Included_hu_sed_soda_data_Changeset
#define _Included_hu_sed_soda_data_Changeset
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_sed_soda_data_Changeset
 * Method:    addCodeElement
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_Changeset_addCodeElement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hu_sed_soda_data_Changeset
 * Method:    addRevision
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_Changeset_addRevision
  (JNIEnv *, jobject, jint);

/*
 * Class:     hu_sed_soda_data_Changeset
 * Method:    refitMatrixSize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_Changeset_refitMatrixSize
  (JNIEnv *, jobject);

/*
 * Class:     hu_sed_soda_data_Changeset
 * Method:    setChange
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_Changeset_setChange
  (JNIEnv *, jobject, jint, jstring, jboolean);

/*
 * Class:     hu_sed_soda_data_Changeset
 * Method:    save
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_Changeset_save
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hu_sed_soda_data_Changeset
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_Changeset_dispose
  (JNIEnv *, jobject);

/*
 * Class:     hu_sed_soda_data_Changeset
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_Changeset_initialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
