/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_sed_soda_data_ResultsMatrix */

#ifndef _Included_hu_sed_soda_data_ResultsMatrix
#define _Included_hu_sed_soda_data_ResultsMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_sed_soda_data_ResultsMatrix
 * Method:    addTestCaseName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_ResultsMatrix_addTestcaseName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hu_sed_soda_data_ResultsMatrix
 * Method:    addRevisionNumber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_ResultsMatrix_addRevisionNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     hu_sed_soda_data_ResultsMatrix
 * Method:    refitMatrixSize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_ResultsMatrix_refitMatrixSize
  (JNIEnv *, jobject);

/*
 * Class:     hu_sed_soda_data_ResultsMatrix
 * Method:    setResult
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_ResultsMatrix_setResult
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     hu_sed_soda_data_ResultsMatrix
 * Method:    save
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_ResultsMatrix_save
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hu_sed_soda_data_ResultsMatrix
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_ResultsMatrix_dispose
  (JNIEnv *, jobject);

/*
 * Class:     hu_sed_soda_data_ResultsMatrix
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_sed_soda_data_ResultsMatrix_initialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
